import type { Metadata } from 'next'
import { Titillium_Web } from 'next/font/google'
import './globals.scss'

const titilium = Titillium_Web({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={titilium.className}>{children}</body>
    </html>
  )
}
